site_name: laminas-config-aggregator
docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - Introduction: intro.md
    - 'Config Providers': config-providers.md
    - Caching: caching.md
site_description: 'Lightweight library for collecting and merging configuration from different sources.'
repo_url: 'https://github.com/laminas/laminas-config-aggregator'
